# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bj12CpdyxXjo-LmXuH_watLyuZ88h1wY
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

def plot_distributions(data, n_rows, n_cols, num_graphs, width, height):
  fig, axs = plt.subplots(4, 4, figsize=(width, height))

  for i in range(n_rows):
    for j in range(n_cols):
      column_index = i*4 + j
      if column_index > num_graphs:
        break
      sns.histplot(data=data, x=data.columns[column_index], ax=axs[i, j])

  plt.show()

def plot_feature_importance(feature_importance, width, height):
  sorted_idx = np.argsort(feature_importance)
  plt.figure(figsize=(width, height))
  features = np.array(X_test.columns)[sorted_idx]
  sns.barplot(x=feature_importance[sorted_idx], y=features, order=features[::-1])
  plt.title('Feature Importance')
  plt.show()